# constants.py

HANDLE_PASSWORD = 1
GET_USERNAME = 2
SET_UP_GAME = 3
GET_TOKENS_COUNT = 4
GET_RED_COUNT = 5
GET_RED_TOKEN_NUMBER = 6
GET_DEMON_TOKEN_NUMBER = 7
GET_RED_TOKEN_RED_NEIGHBORS = 8
CONFIRM_INVITE = 9
START_GAME=10
EXECUTE_TOKEN = 11
GET_RED_TOKEN_RED_NEIGHBORS_IN_GAME = 12